### ISSUE TITLE
react + redux

### ISSUE THREAD

**Issue by KlonD90** [alt-j/fast-react-render#11]
А как можно подключить react-redux? Connect компонент жалуется на 

```
{ Invariant Violation: Could not find "store" in either the context or props of "Connect(Component)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Component)".
    at invariant (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/invariant/invariant.js:42:15)
    at new Connect (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/react-redux/lib/components/connect.js:132:36)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:97:20)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20)
    at renderChildren (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:201:20)
    at renderNativeComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:70:23)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:40:16)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:127:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20)
    at renderChildren (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:201:20)
    at renderNativeComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:70:23)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:40:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:45:20)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:45:20)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:127:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20) name: 'Invariant Violation', framesToPop: 1 } Invariant Violation: Could not find "store" in either the context or props of "Connect(Component)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Component)".
    at invariant (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/invariant/invariant.js:42:15)
    at new Connect (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/react-redux/lib/components/connect.js:132:36)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:97:20)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20)
    at renderChildren (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:201:20)
    at renderNativeComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:70:23)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:40:16)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:127:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20)
    at renderChildren (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:201:20)
    at renderNativeComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:70:23)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:40:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:45:20)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:45:20)
    at renderComponent (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:127:16)
    at renderElement (/Users/nikolajmendaev/Projects/anews-frontend-3/node_modules/fast-react-render/src/index.js:43:20) Could not find "store" in either the context or props of "Connect(Component)". Either wrap the root component in a <Provider>, or explicitly pass "store" as a prop to "Connect(Component)".
```

**Comment by KlonD90** [comment]
С обычным рендерером работает на сервере.

**Comment by alt-j** [comment]
Компонент корректно работает с redux, единственное, что могут быть проблемы с Functional Components, поскольку там некорректно работает передача контекста (исправиться здесь https://github.com/alt-j/fast-react-render/pull/10). 

Судя по ошибке, где-то не передан store. Если у вас ссылка на код проекта, где можно его посмотреть?

**Comment by KlonD90** [comment]
Неа сссылки нету к сожалению.
Store передается + даже дополнительным передал еще раз и попрбовал

**Comment by KlonD90** [comment]
@alt-j пофиксило да те изменения

**Comment by alt-j** [comment]
вмерджу сегодня-завтра

**Comment by alt-j** [comment]
поправлено в fast-react-render@1.2.2
